## Clock
set_property LOC W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.00 [get_ports clk]

## Buttons 
set_property LOC U18 [get_ports btnc] 
set_property IOSTANDARD LVCMOS33 [get_ports btnc] 
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btnc]

## Switches
set_property LOC V17 [get_ports sw[0]] 
set_property IOSTANDARD LVCMOS33 [get_ports sw[1]] 

set_property LOC V17 [get_ports sw[0]] 
set_property IOSTANDARD LVCMOS33 [get_ports sw[1]] 

## LEDs
set_property LOC U16 [get_ports led[0]]
set_property LOC E19 [get_ports led[1]]
set_property LOC U19 [get_ports led[2]]
set_property LOC V19 [get_ports led[3]]
set_property LOC W18 [get_ports led[4]]
set_property LOC U15 [get_ports led[5]]
set_property LOC U14 [get_ports led[6]]
set_property LOC V14 [get_ports led[7]]
set_property LOC V13 [get_ports led[8]]
set_property LOC V3  [get_ports led[9]]
set_property LOC W3  [get_ports led[10]]
set_property LOC U3  [get_ports led[11]]
set_property LOC P3  [get_ports led[12]]
set_property LOC N3  [get_ports led[13]]
set_property LOC P1  [get_ports led[14]]
set_property LOC L1  [get_ports led[15]]

set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports led[10]]
set_property IOSTANDARD LVCMOS33 [get_ports led[11]]
set_property IOSTANDARD LVCMOS33 [get_ports led[12]]
set_property IOSTANDARD LVCMOS33 [get_ports led[13]]
set_property IOSTANDARD LVCMOS33 [get_ports led[14]]
set_property IOSTANDARD LVCMOS33 [get_ports led[15]]

## Seven-Segment Display
set_property LOC W7 [get_ports segment[0]] 
set_property LOC W6 [get_ports segment[1]] 
set_property LOC U8 [get_ports segment[2]] 
set_property LOC V8 [get_ports segment[3]] 
set_property LOC U5 [get_ports segment[4]] 
set_property LOC V5 [get_ports segment[5]] 
set_property LOC U7 [get_ports segment[6]] 
set_property LOC V7 [get_ports segment[7]]
set_property LOC U2 [get_ports anode[0]] 
set_property LOC U4 [get_ports anode[1]] 
set_property LOC V4 [get_ports anode[2]] 
set_property LOC W4 [get_ports anode[3]] 

set_property IOSTANDARD LVCMOS33 [get_ports segment[0]] 
set_property IOSTANDARD LVCMOS33 [get_ports segment[1]] 
set_property IOSTANDARD LVCMOS33 [get_ports segment[2]] 
set_property IOSTANDARD LVCMOS33 [get_ports segment[3]] 
set_property IOSTANDARD LVCMOS33 [get_ports segment[4]] 
set_property IOSTANDARD LVCMOS33 [get_ports segment[5]] 
set_property IOSTANDARD LVCMOS33 [get_ports segment[6]] 
set_property IOSTANDARD LVCMOS33 [get_ports segment[7]]
set_property IOSTANDARD LVCMOS33 [get_ports anode[0]] 
set_property IOSTANDARD LVCMOS33 [get_ports anode[1]] 
set_property IOSTANDARD LVCMOS33 [get_ports anode[2]] 
set_property IOSTANDARD LVCMOS33 [get_ports anode[3]]